<a href="https://colab.research.google.com/github/Dhanapal-Angamuthu/DeepLearning/blob/main/NLP/FakeNewClassificationLSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd


In [12]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/FakeNewsNet.csv')

In [13]:
df.head()

title  \
0  Kandi Burruss Explodes Over Rape Accusation on...   
1  People's Choice Awards 2018: The best red carp...   
2  Sophia Bush Sends Sweet Birthday Message to 'O...   
3  Colombian singer Maluma sparks rumours of inap...   
4  Gossip Girl 10 Years Later: How Upper East Sid...   

                                            news_url        source_domain  \
0  http://toofab.com/2017/05/08/real-housewives-a...           toofab.com   
1  https://www.today.com/style/see-people-s-choic...        www.today.com   
2  https://www.etonline.com/news/220806_sophia_bu...     www.etonline.com   
3  https://www.dailymail.co.uk/news/article-33655...  www.dailymail.co.uk   
4  https://www.zerchoo.com/entertainment/gossip-g...      www.zerchoo.com   

   tweet_num  real  
0         42     1  
1          0     1  
2         63     1  
3         20     1  
4         38     1

In [14]:
df = df.dropna()

In [19]:
### Remove dependant feature or result
X = df.drop('real',axis=1)

In [20]:
## Retrieve dependent feature
y = df['real']

In [21]:
y.shape

(22866,)

In [22]:
X.shape

(22866, 4)

In [23]:
import tensorflow as tf

In [24]:
tf.__version__

'2.19.0'

In [30]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [26]:
voc_size=5000

**One Hot Representation**

In [31]:
message = X.copy()

In [32]:
message.reset_index(inplace=True)

In [33]:
import nltk
import re
from nltk.corpus import stopwords


In [34]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [35]:
## Start doing Data Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', message['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
17866
17867
17868
17869
17870
17871
17872
17873
17874
17875
17876
17877
17878
17879
17880
17881
17882
17883
17884
17885
17886
17887
17888
17889
17890
17891
17892
17893
17894
17895
17896
17897
17898
17899
17900
17901
17902
17903
17904
17905
17906
17907
17908
17909
17910
17911
17912
17913
17914
17915
17916
17917
17918
17919
17920
17921
17922
17923
17924
17925
17926
17927
17928
17929
17930
17931
17932
17933
17934
17935
17936
17937
17938
17939
17940
17941
17942
17943
17944
17945
17946
17947
17948
17949
17950
17951
17952
17953
17954
17955
17956
17957
17958
17959
17960
17961
17962
17963
17964
17965
17966
17967
17968
17969
17970
17971
17972
17973
17974
17975
17976
17977
17978
17979
17980
17981
17982
17983
17984
17985
17986
17987
17988
17989
17990
17991
17992
17993
17994
17995
17996
17997
17998
17999
18000
18001
18002
18003
18004
18005
18006
18007
18008
18009
18010
18011
18012
18013
18014
18015
18016
18017
18018
18019
18020
18021
18022
18023
1

In [36]:
corpus


['kandi burruss explod rape accus real housew atlanta reunion video',
 'peopl choic award best red carpet look',
 'sophia bush send sweet birthday messag one tree hill co star hilari burton breyton eva',
 'colombian singer maluma spark rumour inappropri relationship aunt',
 'gossip girl year later upper east sider shock world chang pop cultur forev',
 'gwen stefani got dump blake shelton jealousi drama exclus',
 'broward counti sheriff fire lie parkland',
 'amber rose shut french montana date rumor call rapper bruvaaa',
 'mindi kale make first post babi appear disneyland wrinkl time co star',
 'katharin mcphee butcher toni nomin drink',
 'wag miami star ashley nicol robert philip wheeler marri',
 'mel gibson hollywood pedophil nowher left hide',
 'medium tyler henri address chill messag kristin cavallari deceas brother express read',
 'dwt season result week disney night',
 'reason tarek el moussa overcom latest back injuri',
 'david cassidi cut estrang daughter kati complet leav son b

In [37]:
onehot_rep = [one_hot(words,voc_size) for words in corpus]
onehot_rep

[[1083, 378, 4117, 4755, 1350, 2422, 3664, 2276, 1647, 3785],
 [709, 1067, 2363, 4024, 3635, 3011, 1760],
 [2034,
  1267,
  1010,
  3644,
  3139,
  5,
  2403,
  2712,
  294,
  4440,
  659,
  1290,
  2619,
  2534,
  4323],
 [803, 4086, 1199, 4495, 62, 4941, 4045, 431],
 [4576,
  2842,
  4764,
  4164,
  2128,
  3043,
  4754,
  3081,
  2342,
  3289,
  4139,
  3550,
  4747],
 [867, 3665, 3633, 2524, 4963, 3507, 454, 254, 4280],
 [1107, 2324, 969, 4546, 2076, 4924],
 [2433, 4209, 2887, 2510, 891, 1122, 4771, 2230, 4229, 2581],
 [4862, 2619, 1824, 2070, 1435, 1807, 2819, 4708, 2719, 2829, 4440, 659],
 [492, 4800, 290, 2767, 3364, 4848],
 [812, 4531, 659, 1575, 4851, 2928, 3080, 2573, 1507],
 [3933, 4775, 3263, 364, 1390, 38, 4684],
 [4344, 1428, 3385, 3944, 4326, 5, 1501, 4546, 3500, 4536, 793, 1157],
 [2328, 2520, 355, 3496, 4663, 4235],
 [348, 4666, 1059, 4185, 2803, 4005, 779, 1187],
 [3060, 1915, 557, 833, 2434, 3130, 1826, 565, 105, 1028],
 [2213, 4941, 925, 1571, 4153, 2398, 462],
 [42

**Embedding Representation**

In [38]:
## Adding padding.. by making every sentens lenght as 20 words
sent_length=20
embedded_docs=pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 2276 1647 3785]
 [   0    0    0 ... 3635 3011 1760]
 [   0    0    0 ... 2619 2534 4323]
 ...
 [   0    0    0 ... 4654 3857 1181]
 [   0    0    0 ... 2527  299 4280]
 [   0    0    0 ... 2143 2537 2363]]


In [39]:
len(embedded_docs)
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1083,
        378, 4117, 4755, 1350, 2422, 3664, 2276, 1647, 3785], dtype=int32)

In [26]:
max_features = 10000
maxlen = 300
batch_size = 256
epochs = 10
embed_size = 100

In [41]:
embedding_vector_features= 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()


Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_11 (LSTM)                  │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [42]:
import numpy as np
len(embedded_docs), y.shape
x_final = np.array(embedded_docs)
y_final = np.array(y)

In [43]:
x_final.shape, y_final.shape

((22866, 20), (22866,))

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_final, y_final, test_size=0.33, random_state=42)


In [45]:
###Model Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.7619 - loss: 0.5386 - val_accuracy: 0.8277 - val_loss: 0.4039
Epoch 2/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8470 - loss: 0.3481 - val_accuracy: 0.8310 - val_loss: 0.3968
Epoch 3/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8728 - loss: 0.3004 - val_accuracy: 0.8293 - val_loss: 0.4273
Epoch 4/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8831 - loss: 0.2775 - val_accuracy: 0.8184 - val_loss: 0.4231
Epoch 5/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8994 - loss: 0.2505 - val_accuracy: 0.8142 - val_loss: 0.4553
Epoch 6/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.9154 - loss: 0.2155 - val_accuracy: 0.8059 - val_loss: 0.5058
Epoch 7/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9201 - loss: 0.1952 - val_accuracy: 0.8024 - val_loss: 0.5529
Epoch 8/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9294 - loss: 0.1786 - val_accuracy:

In [47]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 20, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_11 (LSTM)                  │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 769,505 (2.94 MB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 513,004 (1.96 MB)

In [49]:
## Testing performance
y_pred = (model.predict(X_test) > 0.5).astype("int32")

236/236 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step


In [50]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy:", accuracy)

# Classification report
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[1057  785]
 [ 770 4934]]

Accuracy: 0.7939305592366817

Classification Report:
               precision    recall  f1-score   support

           0       0.58      0.57      0.58      1842
           1       0.86      0.87      0.86      5704

    accuracy                           0.79      7546
   macro avg       0.72      0.72      0.72      7546
weighted avg       0.79      0.79      0.79      7546



In [53]:
###Try with add DropOut Layer
embedding_vector_features = 40
model=Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_12 (LSTM)                  │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [55]:
###Model Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.7526 - loss: 0.5492 - val_accuracy: 0.8240 - val_loss: 0.4067
Epoch 2/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8457 - loss: 0.3585 - val_accuracy: 0.8351 - val_loss: 0.3928
Epoch 3/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8699 - loss: 0.3085 - val_accuracy: 0.8313 - val_loss: 0.4092
Epoch 4/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.8802 - loss: 0.2819 - val_accuracy: 0.8269 - val_loss: 0.4312
Epoch 5/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8869 - loss: 0.2674 - val_accuracy: 0.8214 - val_loss: 0.4493
Epoch 6/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9004 - loss: 0.2410 - val_accuracy: 0.8167 - val_loss: 0.4748
Epoch 7/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.9046 - loss: 0.2257 - val_accuracy: 0.8098 - val_loss: 0.4996
Epoch 8/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9159 - loss: 0.2092 - val_accuracy

In [56]:
model.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 20, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 20, 40)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_12 (LSTM)                  │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 769,505 (2.94 MB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 513,004 (1.96 MB)

In [57]:
## Testing performance
y_pred = (model.predict(X_test) > 0.5).astype("int32")

236/236 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy:", accuracy)

# Classification report
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Confusion Matrix:
 [[1026  816]
 [ 652 5052]]

Accuracy: 0.8054598462761728

Classification Report:
               precision    recall  f1-score   support

           0       0.61      0.56      0.58      1842
           1       0.86      0.89      0.87      5704

    accuracy                           0.81      7546
   macro avg       0.74      0.72      0.73      7546
weighted avg       0.80      0.81      0.80      7546

